In [1]:
import numpy as np

体素划分[3,5,2]
A  活度矩阵       [3, 5]
CE 发射计数率矩阵  [3, 5]
F  探测效率矩阵    [5, 3]
CE = A * F
A = CE * F^-1

In [24]:
CE = np.array([(0,	7.45E-07,	7.00E-07,	6.05E-07,	0.00E+00),
              (0,	6.55E-07,	4.89E-06,	6.10E-07,	0),
              (0,	6.10E-07,	7.15E-07,	6.55E-07,	0.00E+00)])

F = np.array([(0,	7.45E-07,	7.00E-07,	6.05E-07,	0.00E+00),
              (0,	6.55E-07,	4.89E-06,	6.10E-07,	0),
              (0,	6.10E-07,	7.15E-07,	6.55E-07,	0.00E+00)])

A = np.zeros([3,4])

E = np.zeros([3,5])




a = np.array([[1, 2], [3, 5]])
b = np.array([1, 2])
x = np.linalg.solve(a, b)

CE = CE * 1e8 *2
print(CE)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[  0. 149. 140. 121.   0.]
 [  0. 131. 978. 122.   0.]
 [  0. 122. 143. 131.   0.]]
